In [1]:
import tensorflow as tf
import numpy as np
from termcolor import colored
print(f"Tensorflow version: {tf.__version__}")

Tensorflow version: 2.11.0


In [2]:
def normalize(tensor):
    tensor_minusmin = tensor - tensor.min()
    tensor_maxminusmin = tensor.max() - tensor.min()
    return tensor_minusmin / tensor_maxminusmin

In [3]:
# Read the raw audio from the .WAV file
raw_audio = tf.io.read_file(filename="./audio_data/ENVELO01.WAV")
# Convert the raw audio to a waveform
wave_bank, sample_rate = tf.audio.decode_wav(raw_audio)
# Display the wavebank and sample_rate
display(wave_bank, sample_rate)

<tf.Tensor: shape=(16384, 1), dtype=float32, numpy=
array([[-0.12615967],
       [-0.51693726],
       [ 0.15652466],
       ...,
       [-0.9361267 ],
       [-0.9999695 ],
       [-0.9085388 ]], dtype=float32)>

<tf.Tensor: shape=(), dtype=int32, numpy=44100>

In [4]:
wave_size = 256
num_waves = 0
waves = []
wave_forms = np.transpose(wave_bank.numpy())
for i in range(64):
    wave_form = wave_forms[0, i*wave_size:i*wave_size+wave_size]
    if wave_form.max() != wave_form.min():
        wave_form = normalize(wave_form)
        waves.append(wave_form)
        num_waves += 1    
waves = tf.stack(waves)
display(waves)

<tf.Tensor: shape=(64, 256), dtype=float32, numpy=
array([[0.46670794, 0.2579909 , 0.61769164, ..., 0.04562273, 0.        ,
        0.06958321],
       [0.41013354, 0.29407066, 0.5739569 , ..., 0.0447096 , 0.        ,
        0.06817456],
       [0.41012698, 0.29405   , 0.5739478 , ..., 0.04470889, 0.        ,
        0.06817347],
       ...,
       [0.84161735, 1.        , 0.49794096, ..., 0.04799939, 0.        ,
        0.06150281],
       [0.84177154, 1.        , 0.4982089 , ..., 0.0480049 , 0.        ,
        0.06150987],
       [0.84177154, 1.        , 0.49818975, ..., 0.04007433, 0.        ,
        0.05739134]], dtype=float32)>

In [ ]:
# "./audio_data/ENVELO01.WAV"
def get_waves(file_name):
    # Read the raw audio from the .WAV file
    raw_audio = tf.io.read_file(filename=file_name)
    # Convert the raw audio to a waveform
    wave_bank, sample_rate = tf.audio.decode_wav(raw_audio)
    # Display the wavebank and sample_rate
    # display(wave_bank, sample_rate)
    wave_size = 256
    num_waves = 0
    waves = []
    wave_forms = np.transpose(wave_bank.numpy())
    for i in range(64):
        wave_form = wave_forms[0, i*wave_size:i*wave_size+wave_size]
        if wave_form.max() != wave_form.min():
            wave_form = normalize(wave_form)
            waves.append(wave_form)
            num_waves += 1    
    waves = tf.stack(waves)
    return waves